-- 사용자 데이터 삽입
INSERT INTO MEMBER (ENROLL_DATE, M_EMAIL, M_GRADE, M_ID, M_NAME, M_PHONE, M_PW)
SELECT '20250411', 'admin@gmail.com', 'ADMIN', 'admin', '관리자', '01027388240', '1234'
    WHERE NOT EXISTS (SELECT 1 FROM MEMBER WHERE M_ID = 'admin');

INSERT INTO MEMBER (ENROLL_DATE, M_EMAIL, M_GRADE, M_ID, M_NAME, M_PHONE, M_PW)
SELECT '20250411', 'shlim@gmail.com', 'USER', 'shlim', '임소현', '01027388240', '1234'
    WHERE NOT EXISTS (SELECT 1 FROM MEMBER WHERE M_ID = 'shlim');

-- 카테고리 데이터 삽입
INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME)
SELECT 1000, 1000, '디자인'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 1000);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME)
SELECT 1000, 1100, '로고·브랜딩'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 1100);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME)
SELECT 1000, 1200, '캘리그라피·폰트'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 1200);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME)
SELECT 1000, 1300, '일러스트·캐리커쳐'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 1300);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME)
SELECT 1000, 1400, '이벤트·상세 페이지'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 1400);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME)
SELECT 1000, 1500, '간판·시공'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 1500);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME)
SELECT 1000,  1600, '인쇄·홍보물·배너'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 1600);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME)
SELECT 2000, 2000, 'IT·프로그래밍'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 2000);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME)
SELECT 2000, 2100, '워드프레스'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 2100);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME)
SELECT 2000, 2200, '웹사이트개발'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 2200);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME)
SELECT 2000, 2300, '프로그램개발'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 2300);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME)
SELECT 2000, 2400, '데이터베이스'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 2400);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME)
SELECT 2000,2500, '게임개발'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 2500);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME)
SELECT 2000, 2600, '파일변환'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 2600);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME)
SELECT 3000, 3000, '비즈니스컨설팅'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 3000);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME)
SELECT 3000,3100, '사업계획서·투자제안서'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 3100);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME)
SELECT 3000, 3200, '인사·노무'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 3200);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME)
SELECT 3000,3300, '창업컨설팅'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 3300);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME)
SELECT 3000, 3400, '법률법무'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 3400);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME)
SELECT 3000, 3500, '업무지원·CS'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 3500);

INSERT INTO CATEGORY (C_DIVISION_NO, C_NO, C_NAME)
SELECT 3000, 3600, '컨설팅'
    WHERE NOT EXISTS (SELECT 1 FROM CATEGORY WHERE C_NO = 3600);
