--사용자
INSERT INTO MEMBER (ENROLL_DATE, M_EMAIL, M_GRADE, M_ID, M_NAME, M_PHONE, M_PW) VALUES ('20250411', 'admin@gmail.com', '0', 'admin','관리자', '01027388240', '1234');
INSERT INTO MEMBER (ENROLL_DATE, M_EMAIL, M_GRADE, M_ID, M_NAME, M_PHONE, M_PW) VALUES ('20250411', 'shlim@gmail.com', '1', 'shlim','임소현', '01027388240', '1234');

--카테고리
INSERT INTO CATEGORY (C_DIVISION_NO, C_DIVISION_NAME, C_NO, C_NAME) VALUES (1000, '디자인 카테고리', 1100, '로고·브랜딩');
INSERT INTO CATEGORY (C_DIVISION_NO, C_DIVISION_NAME, C_NO, C_NAME) VALUES (1000, '디자인 카테고리', 1200, '캘리그라피·폰트');
INSERT INTO CATEGORY (C_DIVISION_NO, C_DIVISION_NAME, C_NO, C_NAME) VALUES (1000, '디자인 카테고리', 1300, '일러스트·캐리커쳐');
INSERT INTO CATEGORY (C_DIVISION_NO, C_DIVISION_NAME, C_NO, C_NAME) VALUES (1000, '디자인 카테고리', 1400, '이벤트·상세 페이지');
INSERT INTO CATEGORY (C_DIVISION_NO, C_DIVISION_NAME, C_NO, C_NAME) VALUES (1000, '디자인 카테고리', 1500, '간판·시공');
INSERT INTO CATEGORY (C_DIVISION_NO, C_DIVISION_NAME, C_NO, C_NAME) VALUES (1000, '디자인 카테고리', 1600, '인쇄·홍보물·배너');

INSERT INTO CATEGORY (C_DIVISION_NO, C_DIVISION_NAME, C_NO, C_NAME) VALUES (2000, 'IT·프로그래밍 카테고리', 2100, '워드프레스');
INSERT INTO CATEGORY (C_DIVISION_NO, C_DIVISION_NAME, C_NO, C_NAME) VALUES (2000, 'IT·프로그래밍 카테고리', 2200, '웹사이트개발');
INSERT INTO CATEGORY (C_DIVISION_NO, C_DIVISION_NAME, C_NO, C_NAME) VALUES (2000, 'IT·프로그래밍 카테고리', 2300, '프로그램개발');
INSERT INTO CATEGORY (C_DIVISION_NO, C_DIVISION_NAME, C_NO, C_NAME) VALUES (2000, 'IT·프로그래밍 카테고리', 2400, '데이터베이스');
INSERT INTO CATEGORY (C_DIVISION_NO, C_DIVISION_NAME, C_NO, C_NAME) VALUES (2000, 'IT·프로그래밍 카테고리', 2500, '게임개발');
INSERT INTO CATEGORY (C_DIVISION_NO, C_DIVISION_NAME, C_NO, C_NAME) VALUES (2000, 'IT·프로그래밍 카테고리', 2600, '파일변환');

INSERT INTO CATEGORY (C_DIVISION_NO, C_DIVISION_NAME, C_NO, C_NAME) VALUES (3000, '비즈니스컨설팅 카테고리', 3100, '사업계획서·투자제안서');
INSERT INTO CATEGORY (C_DIVISION_NO, C_DIVISION_NAME, C_NO, C_NAME) VALUES (3000, '비즈니스컨설팅 카테고리', 3200, '인사·노무');
INSERT INTO CATEGORY (C_DIVISION_NO, C_DIVISION_NAME, C_NO, C_NAME) VALUES (3000, '비즈니스컨설팅 카테고리', 3300, '창업컨설팅');
INSERT INTO CATEGORY (C_DIVISION_NO, C_DIVISION_NAME, C_NO, C_NAME) VALUES (3000, '비즈니스컨설팅 카테고리', 3400, '법률법무');
INSERT INTO CATEGORY (C_DIVISION_NO, C_DIVISION_NAME, C_NO, C_NAME) VALUES (3000, '비즈니스컨설팅 카테고리', 3500, '업무지원·CS');
INSERT INTO CATEGORY (C_DIVISION_NO, C_DIVISION_NAME, C_NO, C_NAME) VALUES (3000, '비즈니스컨설팅 카테고리', 3600, '컨설팅');
